# Generated by Django 5.2.7 on 2025-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
