# Generated by Django 5.2.7 on 2025-10-09 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_remove_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_cny',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_kzt',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
